apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-deployments
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: 'https://github.com/ArshadGhazi/argorepository.git'
    targetRevision: HEAD
    path: .
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
